version: '3.8'

services:

  kenyaqui-1:
    image: kenyaqui:1.0
    container_name: kenyaqui-1
    tty: true                                         
    user: root                                        

  nginx-proxy:
    image: nginx:latest
    container_name: nginx-proxy                       
    depends_on:
      - kenyaqui-1                                 
    ports:
      - "80:8080"                                     
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro   
    tty: true                                         
    user: root   
